[package]
name = "resettable-derive"
version = "1.0.0"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["derive", "parsing"] }
quote = "1.0"
